const userDanaMastergroups = [{
        id: 1,
        groupTitle: "למידה למבחן בקורס אלגוריתמים",
        groupDescription: 'נפתור במהלך המפגש את מבחן תש"פ סמסטר א מועד א. אם יישאר זמן אז גם נדון על הטעויות של כל אחד ואחת ונסיק מסקנות.',
        groupPurpose: "למידה למבחן",
        maxGroupSize: 5,
        currentGroupSize: 2,
        date: new Date(2021, 7, 20),
        startHour: "09:00",
        endHour: "13:00",
        meetingType: "פרונטלית",
        city: "תל-אביב",
        place: "ספריית מדעים מדויקים באוניברסיטת תל-אביב",
        link: null,
        institution: "אוניברסיטת תל-אביב",
        people: [{
                id: 1,
                name: "Dana Master",
                photo: "https://images.unsplash.com/photo-1544507888-56d73eb6046e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80",
            },
            {
                id: 2,
                name: "נעמה ניסן",
                photo: "https://randomuser.me/api/portraits/women/94.jpg",
            },
            {
                id: 3,
                name: "איתי לוי",
                photo: "https://randomuser.me/api/portraits/men/14.jpg",
            },
        ],
    },
    {
        id: 2,
        groupTitle: "מודלים חישוביים - חזרה על אוטומט מחסנית",
        groupDescription: "נעבור שוב על המצגת מהשיעור, נדון על הנושא ונפתור מספר שאלות חזרה.",
        groupPurpose: "חזרה על החומר",
        maxGroupSize: 8,
        currentGroupSize: 6,
        date: new Date(2021, 4, 11),
        startHour: "08:00",
        endHour: "11:30",
        meetingType: "וירטואלית",
        city: null,
        place: null,
        link: "https://meet.google.com/",
        institution: "אוניברסיטת בן-גוריון",
        people: [{
                id: 1,
                name: "Dana Master",
                photo: "https://images.unsplash.com/photo-1544507888-56d73eb6046e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80",
            },
            {
                id: 2,
                name: "יואב בן חיים",
                photo: "https://randomuser.me/api/portraits/men/37.jpg",
            },
            {
                id: 3,
                name: "שירה כהן",
                photo: "https://randomuser.me/api/portraits/women/63.jpg",
            },
            {
                id: 4,
                name: "נעמה ניסן",
                photo: "https://randomuser.me/api/portraits/women/94.jpg",
            },
            {
                id: 5,
                name: "איתי לוי",
                photo: "https://randomuser.me/api/portraits/men/14.jpg",
            },
            {
                id: 6,
                name: "ניר אברמוב",
                photo: "https://randomuser.me/api/portraits/men/46.jpg",
            },
            {
                id: 7,
                name: "הילה נחמיאס",
                photo: "https://randomuser.me/api/portraits/women/68.jpg",
            },
        ],
    },
];

export default userDanaMastergroups;