export const major_minor = [
    { id: "Computer Science", name: "מדעי המחשב" },
    { id: "Mathematics", name: "מתמטיקה" },
    { id: "Statistics & Performance analysis", name: "סטטיסטיקה וחקר ביצועים" },
    { id: "Chemistry", name: "כימיה" },
    { id: "Enviroment studies", name: "לימודי סביבה" },
    { id: "Geography and man enviroment", name: "גיאוגרפיה וסביבת האדם" },
    { id: "Geophysics", name: "גיאופיזיקה" },
    { id: "Physics and astronomy", name: "פיזיקה ואסטרונומיה" },
    { id: "Law", name: "משפטים" },
    { id: "Managment", name: "ניהול" },
    { id: "MD", name: "רפואה" },
    { id: "Dentist", name: "רפואת שיניים" },
    { id: "Physiotherapy", name: "פיזיותרפיה" },
    { id: "Occupational Therapy", name: "ריפוי בעיסוק" },
    { id: "Nursing", name: "סיעוד" },
    { id: "Communication Defects", name: "הפרעות בתקשורת" },
    { id: "Public health", name: "בריאות הציבור" },
    { id: "Epidemiology", name: "אפידימיולוגיה" },
    { id: "Social Work", name: "עבודה סוציאלית" },
    { id: "Education", name: "חינוך" },
    { id: "Special Education", name: "חינוך מיוחד" },
    { id: "Brain Studies", name: "מדעי המוח" },
    { id: "English as a foreign language", name: "אנגלית כשפה זרה" },
    { id: "Cyber", name: "סייבר" },
    { id: "Biology", name: "ביולוגיה" },
    { id: "Plant Studies", name: "מדעי הצמח" },
    { id: "Biochemistry", name: "ביוכימיה" },
    { id: "Zoology", name: "זואולוגיה" },
    { id: "Cell analysis and Immunology", name: "חקר התא ואימונולוגיה" },
    {
        id: "Molecular microbiology and biotechnology",
        name: "מיקרוביולוגיה מולקולרית וביוטכנולוגיה",
    },
    { id: "Neurobiochemistry", name: "נוירוביוכימיה" },
    { id: "Electrical Engineering", name: "הנדסת חשמל ואלקטרוניקה" },
    { id: "Computer Engineering", name: "הנדסת מחשבים ותוכנה" },
    { id: "Mechanical Engineering", name: "הנדסה מכנית" },
    { id: "Bio-medical Engineering", name: "הנדסה ביו-רפואית" },
    { id: "Industry Engineering", name: "הנדסת תעשייה" },
    { id: "Enviroment Engineering", name: "הנדסת סביבה" },
    { id: "System Engineering", name: "הנדסת מערכות" },
    { id: "Hi-tech science", name: "מדעים להייטק" },
    { id: "Theatre", name: "תיאטרון" },
    { id: "Heritage and culture", name: "שימור המורשת הבנויה ונופי התרבות" },
    { id: "Creation in arts", name: "הבעה ויצירה באמנויות" },
    { id: "Art history", name: "תולדות האמנות" },
    { id: "Musicology", name: "מוזיקולוגיה" },
    { id: "Music", name: "מוזיקה" },
    { id: "Film and Television", name: "קולנוע וטלוויזיה" },
    { id: "Architecture", name: "אדריכלות" },
    { id: "Heritage certificate", name: "לימודי תעודה בשימור המורשת הבנויה" },
    { id: "Museology certificate", name: "לימודי תעודה במוזיאולוגיה" },
    { id: "English", name: "אנגלית" },
    { id: "Archeology", name: "ארכיאולוגיה ותרבויות המזרח הקדום" },
    { id: "General Linguistics", name: "בלשנות כללית" },
    { id: "Geography", name: "גיאוגרפיה וסביבת האדם" },
    { id: "History", name: "היסטוריה כללית" },
    {
        id: "Middle East and Africa History",
        name: "היסטוריה של המזרח התיכון ואפריקה",
    },
    { id: "Africa", name: "לימודי אפריקה" },
    { id: "Israel History", name: "היסטוריה של עם ישראל" },
    {
        id: "History & Philosophy of science and ideas",
        name: "היסטוריה ופילוסופיה של המדעים והרעיונות",
    },
    { id: "Arabic and Islam", name: "לימודי הערבית ואסלאם" },
    { id: "Classic studies", name: "לימודים קלאסיים" },
    { id: "East Asia Studies", name: "לימודי מזרח אסיה" },
    {
        id: "Hebrew tongue and semit Linguistics",
        name: "הלשון העברית ובלשנות שמית",
    },
    { id: "Scripture", name: "מקרא" },
    { id: "Translation Certificate", name: "לימודי תעודה בתרגום ועריכת תרגום" },
    { id: "Literature", name: "ספרות" },
    { id: "Phylosophy", name: "פילוסופיה" },
    { id: "Jewish phylosophy and Talmud", name: "פילוסופיה יהודית ותלמוד" },
    { id: "Pacam", name: "פכ''מ" },
    { id: "French", name: "צרפתית" },
    { id: "Multidisciplinary", name: "רב-תחומי מדעי הרוח" },
    { id: "Women and gender", name: "לימודי נשים ומגדר" },
    { id: "Youth and teen research", name: "מחקר תרבות הילד והנוער" },
    { id: "Religious science", name: "מדעי הדתות" },
    { id: "Culture Science", name: "מדעי התרבות" },
    {
        id: "Cognitive language use studies",
        name: "לימודים קוגנטיביים של השפה ושימושיה",
    },
    { id: "Grammatical edit certificate", name: "לימודי תעודה - עריכה לשונית" },
    {
        id: "Middle East of our time studies",
        name: "לימודי המזרח התיכון בן-זמננו",
    },
    { id: "Language Teaching", name: "הוראת שפות" },
];

export const degree = [
    { id: "Unassigned", name: "אחר" },
    { id: "B.ABS.C", name: "ראשון" },
    { id: "M.A", name: "שני" },
    { id: "Ph.D", name: "דוקטורט" },
];

export const institutions = [
    { id: "Unassigned", name: "אחר" },
    { id: "TAU", name: "אוניברסיטת תל-אביב" },
    { id: "IIT", name: "הטכניון" },
    { id: "HUJI", name: "האוניברסיטה העברית" },
    { id: "BGU", name: "אוניברסיטת בן-גוריון בנגב" },
    { id: "AUS", name: "אוניברסיטת אריאל שבשומרון" },
    { id: "BIU", name: "אוניברסיטת בר-אילן" },
    { id: "HAU", name: "אוניברסיטת חיפה" },
    { id: "Open", name: "האוניברסיטה הפתוחה" },
    { id: "AfC", name: "מכללת אפקה" },
    { id: "AhvaC", name: "המכללה האקדמית אחוה" },
    { id: "AshC", name: "המכללה האקדמית אשקלון" },
    { id: "WinC", name: "המכללה האקדמית בוינגייט" },
    { id: "BBC", name: "המכללה האקדמית בית-ברל" },
    { id: "WGC", name: "המכללה האקדמית גליל מערבי" },
    { id: "HadasaC", name: "המכללה האקדמית הדסה" },
    { id: "KineretC", name: "מכללת כנרת" },
    { id: "SMC", name: "מכללת סמי שמעון להנדסה" },
    { id: "OBC", name: "אורט בראודה" },
    { id: "SKC", name: "סמינר הקיבוצים" },
    { id: "SAC", name: "המכללה האקדמית ספיר" },
    { id: "THC", name: "מכללת תל-חי" },
    { id: "TYC", name: "המכללה האקדמית תל-אביב - יפו" },
    { id: "MC", name: "המכללה למנהל" },
    { id: "PC", name: "המרכז האקדמי פרס" },
    { id: "RP", name: "המרכז האקדמי רופין" },
    { id: "LEC", name: "שערי משפט" },
    { id: "OnoC", name: "הקריה האקדמית אונו" },
    { id: "WI", name: "מכון ויצמן למדע" },
    { id: "HIT", name: "מכון טכנולוגי חולון" },
    { id: "LskC", name: "מכללת לוינסקי לחינוך" },
    { id: "ShC", name: "שנקר" },
];